name: Aimers
channels:
  - conda-forge
dependencies:
  - python==3.9
  - pip
  - numpy
  - pandas
  - scikit-learn
  - catboost
  - lightgbm
  - xgboost
  - ipykernel
  - matplotlib
  - seaborn
  - wordcloud

  # - pip:
  #   - --extra-index-url https://download.pytorch.org/whl/cu113
  #   - torch==1.10.1+cu113
  #   - --extra-index-url https://download.pytorch.org/whl/cu113
  #   - torchvision==0.11.2+cu113
